export const products = [
    {
      id: 1,
      name: 'Fastrack Blue Rectangle Rimmed Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 1000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/i/black-full-rim-square-lenskart-air-fusion-la-e13069-c1-eyeglasses_lenskart-air-la-e13033-c1-eyeglasses_eyeglasses_g_7875_1b_28july23.jpg',
      brand: 'Fastrack',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 2,
      name: 'Fastrack Brown Wayfarer Rimmed Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 1000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/pink-gold-pink-full-rim-cat-eye-john-jacobs-tr-flex-jj-e-14409-c6-eyeglasses__dsc5656.jpg',
      brand: 'Fastrack',
      category: 'Full Rim',
      color: 'Brown',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Wayfarer',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 3,
      name: 'Ray-Ban Aviator Sunglasses',
      description: 'For Men and Women, Size: Large',
      price: 5000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/pink-gold-pink-full-rim-cat-eye-john-jacobs-tr-flex-jj-e-14409-c6-eyeglasses__dsc5656.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Gold',
      frameSize: 'Large',
      gender: 'Unisex',
      frameShape: 'Aviator',
      material: 'Metal',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 4,
      name: 'Oakley Sport Sunglasses',
      description: 'For Men, Size: Medium',
      price: 4000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e10235-c7-eyeglasses_g_2375_image_pla.jpg',
      brand: 'Oakley',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 5,
      name: 'Tom Ford FT5634-B Eyeglasses',
      description: 'For Women, Size: Medium',
      price: 7000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/black-gold-black-full-rim-round-john-jacobs-tr-flex-jj-e14410-c6-eyeglasses__dsc7005_20_06_2024.jpg',
      brand: 'Tom Ford',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Women',
      frameShape: 'Cat Eye',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Progressive',
      supportedPowers: '-4.00 to +3.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 6,
      name: 'Vogue VO5165 Eyeglasses',
      description: 'For Women, Size: Small',
      price: 3000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e13346-c2-eyeglasses_g_5793.jpg',
      brand: 'Vogue',
      category: 'Full Rim',
      color: 'Red',
      frameSize: 'Small',
      gender: 'Women',
      frameShape: 'Round',
      material: 'Plastic',
      frameWidth: 'Narrow',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Classic',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 135,
      productType: 'Eyeglasses'
    },
    {
      id: 7,
      name: 'Carrera 1001/S Sunglasses',
      description: 'For Men, Size: Large',
      price: 4500,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/i/pink-transparent-full-rim-cat-eye-lenskart-air-fusion-la-e14101-c2-eyeglasses_lenskart-air-la-e14101-c2-c2-eyeglasses_g_7523_28july23.jpg',
      brand: 'Carrera',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 8,
      name: 'John Jacobs Supreme Steel Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 3500,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/gunmetal--black-full-rim-rectangle-john-jacobs-supreme-steel-jj-e11540-c6-eyeglasses_g_7769_25_04_2023.jpg',
      brand: 'John Jacobs',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Square',
      material: 'Metal',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 9,
      name: 'Ray-Ban Clubmaster Sunglasses',
      description: 'For Men and Women, Size: Medium',
      price: 5500,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/Purple-Silver-Purple-Transparent-Full-Rim-Round-Vincent-Chase-SLEEK-STEEL-VC-E13784-C1-Eyeglasses_vincent-chase-vc-e13784-c1-eyeglasses_g_301709_02_2022.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Brown',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Clubmaster',
      material: 'Metal',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 10,
      name: 'Titan Oval Rimmed Eyeglasses',
      description: 'For Women, Size: Medium',
      price: 2000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/i/sky-blue-full-rim-square-lenskart-air-fusion-la-e13069-c2-eyeglasses_lenskart-air-la-e13033-c2-eyeglasses_eyeglasses_g_3587_2_05_july23.jpg',
      brand: 'Titan',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Women',
      frameShape: 'Oval',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 11,
      name: 'Fastrack Rectangle Rimmed Eyeglasses',
      description: 'For Men, Size: Medium',
      price: 1500,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/i/transparent-gold-full-rim-rectangle-lenskart-air-fusion-la-e12709-c2-eyeglasses_csvfile-1690431879411-transparent-gold-full-rim-rectangle-lenskart-air-signia-la-e12709-c2-eyeglasses_csvfile-1652945002382-g_4082.jpg',
      brand: 'Fastrack',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 12,
      name: 'Ray-Ban Round Sunglasses',
      description: 'For Men and Women, Size: Medium',
      price: 4800,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/i/transparent-full-rim-rectangle-lenskart-air-classic-la-e15019-c3-eyeglasses_g_8694_09_09_2022.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Round',
      material: 'Metal',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 13,
      name: 'Oakley Holbrook Sunglasses',
      description: 'For Men, Size: Large',
      price: 6000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/i/black-gunmetal-black-full-rim-wayfarer-lenskart-air-fusion-la-e13068---c1-eyeglasses_lenskart-air-la-e13032-c1-eyeglasses_g_2000_05_july23.jpg',
      brand: 'Oakley',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Square',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 14,
      name: 'Tom Ford FT5294 Eyeglasses',
      description: 'For Women, Size: Medium',
      price: 8000,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/silver-black-full-rim-square-vincent-chase-sleek-steel-vc-e12422-c3-eyeglasses_csvfile-1710576960062-img_2056.jpg',
      brand: 'Tom Ford',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Women',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Progressive',
      supportedPowers: '-4.00 to +3.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 15,
      name: 'Vogue VO4178 Eyeglasses',
      description: 'For Women, Size: Small',
      price: 3200,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/silver-transparent-full-rim-round-vincent-chase-sleek-steel-vc-e15069-c1-eyeglasses_g_3598_10_14_22.jpg',
      brand: 'Vogue',
      category: 'Full Rim',
      color: 'Red',
      frameSize: 'Small',
      gender: 'Women',
      frameShape: 'Oval',
      material: 'Plastic',
      frameWidth: 'Narrow',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Classic',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 135,
      productType: 'Eyeglasses'
    },
    {
      id: 16,
      name: 'Carrera 1011/S Sunglasses',
      description: 'For Men, Size: Large',
      price: 4800,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/grey-transparent-grey-full-rim-wayfarer-john-jacobs-rich-acetate-jj-e11727--c6-eyeglasses_img_7072_24_02_2024.jpg',
      brand: 'Carrera',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Aviator',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 17,
      name: 'John Jacobs Wayfarer Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 3600,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/i/Lenskart-Air-LA-E14362-C3-Eyeglasses_J_1886.jpg',
      brand: 'John Jacobs',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Wayfarer',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 18,
      name: 'Ray-Ban Classic Wayfarer Sunglasses',
      description: 'For Men and Women, Size: Medium',
      price: 5800,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/transparent-silver-blue-full-rim-rectangle-john-jacobs-tr-flex-jj-e14416-c5-eyeglasses__dsc7014_20_06_2024.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Wayfarer',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 19,
      name: 'Titan Oval Rimmed Eyeglasses',
      description: 'For Men, Size: Medium',
      price: 1800,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/gold-black-half-rim-rectangle-john-jacobs-supreme-steel-jj-e11678-c8-eyeglasses_g_0849_02_14_23.jpg',
      brand: 'Titan',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Men',
      frameShape: 'Oval',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 20,
      name: 'Oakley Crosslink Zero Eyeglasses',
      description: 'For Men, Size: Large',
      price: 5200,
      image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/grey-transparent-grey-full-rim-wayfarer-john-jacobs-rich-acetate-jj-e11727--c6-eyeglasses_img_7072_24_02_2024.jpg',
      brand: 'Oakley',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-4.00 to +3.00',
      collection: 'Sport',
      glassColor: 'Clear',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Eyeglasses'
    }
  ];
  