export const products = [
    {
      id: 1,
      name: 'Fastrack Blue Rectangle Rimmed Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 1000,
      image: 'path_to_image_1.jpg',
      brand: 'Fastrack',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 2,
      name: 'Fastrack Brown Wayfarer Rimmed Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 1000,
      image: 'path_to_image_2.jpg',
      brand: 'Fastrack',
      category: 'Full Rim',
      color: 'Brown',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Wayfarer',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 3,
      name: 'Ray-Ban Aviator Sunglasses',
      description: 'For Men and Women, Size: Large',
      price: 5000,
      image: 'path_to_image_3.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Gold',
      frameSize: 'Large',
      gender: 'Unisex',
      frameShape: 'Aviator',
      material: 'Metal',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 4,
      name: 'Oakley Sport Sunglasses',
      description: 'For Men, Size: Medium',
      price: 4000,
      image: 'path_to_image_4.jpg',
      brand: 'Oakley',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 5,
      name: 'Tom Ford FT5634-B Eyeglasses',
      description: 'For Women, Size: Medium',
      price: 7000,
      image: 'path_to_image_5.jpg',
      brand: 'Tom Ford',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Women',
      frameShape: 'Cat Eye',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Progressive',
      supportedPowers: '-4.00 to +3.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 6,
      name: 'Vogue VO5165 Eyeglasses',
      description: 'For Women, Size: Small',
      price: 3000,
      image: 'path_to_image_6.jpg',
      brand: 'Vogue',
      category: 'Full Rim',
      color: 'Red',
      frameSize: 'Small',
      gender: 'Women',
      frameShape: 'Round',
      material: 'Plastic',
      frameWidth: 'Narrow',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Classic',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 135,
      productType: 'Eyeglasses'
    },
    {
      id: 7,
      name: 'Carrera 1001/S Sunglasses',
      description: 'For Men, Size: Large',
      price: 4500,
      image: 'path_to_image_7.jpg',
      brand: 'Carrera',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 8,
      name: 'John Jacobs Supreme Steel Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 3500,
      image: 'path_to_image_8.jpg',
      brand: 'John Jacobs',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Square',
      material: 'Metal',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 9,
      name: 'Ray-Ban Clubmaster Sunglasses',
      description: 'For Men and Women, Size: Medium',
      price: 5500,
      image: 'path_to_image_9.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Brown',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Clubmaster',
      material: 'Metal',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 10,
      name: 'Titan Oval Rimmed Eyeglasses',
      description: 'For Women, Size: Medium',
      price: 2000,
      image: 'path_to_image_10.jpg',
      brand: 'Titan',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Women',
      frameShape: 'Oval',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 11,
      name: 'Fastrack Rectangle Rimmed Eyeglasses',
      description: 'For Men, Size: Medium',
      price: 1500,
      image: 'path_to_image_11.jpg',
      brand: 'Fastrack',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 12,
      name: 'Ray-Ban Round Sunglasses',
      description: 'For Men and Women, Size: Medium',
      price: 4800,
      image: 'path_to_image_12.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Round',
      material: 'Metal',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 13,
      name: 'Oakley Holbrook Sunglasses',
      description: 'For Men, Size: Large',
      price: 6000,
      image: 'path_to_image_13.jpg',
      brand: 'Oakley',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Square',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 14,
      name: 'Tom Ford FT5294 Eyeglasses',
      description: 'For Women, Size: Medium',
      price: 8000,
      image: 'path_to_image_14.jpg',
      brand: 'Tom Ford',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Women',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Progressive',
      supportedPowers: '-4.00 to +3.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 15,
      name: 'Vogue VO4178 Eyeglasses',
      description: 'For Women, Size: Small',
      price: 3200,
      image: 'path_to_image_15.jpg',
      brand: 'Vogue',
      category: 'Full Rim',
      color: 'Red',
      frameSize: 'Small',
      gender: 'Women',
      frameShape: 'Oval',
      material: 'Plastic',
      frameWidth: 'Narrow',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Classic',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 135,
      productType: 'Eyeglasses'
    },
    {
      id: 16,
      name: 'Carrera 1011/S Sunglasses',
      description: 'For Men, Size: Large',
      price: 4800,
      image: 'path_to_image_16.jpg',
      brand: 'Carrera',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Aviator',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Sport',
      glassColor: 'Polarized',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Sunglasses'
    },
    {
      id: 17,
      name: 'John Jacobs Wayfarer Eyeglasses',
      description: 'For Men and Women, Size: Medium',
      price: 3600,
      image: 'path_to_image_17.jpg',
      brand: 'John Jacobs',
      category: 'Full Rim',
      color: 'Blue',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Wayfarer',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 18,
      name: 'Ray-Ban Classic Wayfarer Sunglasses',
      description: 'For Men and Women, Size: Medium',
      price: 5800,
      image: 'path_to_image_18.jpg',
      brand: 'Ray-Ban',
      category: 'Sunglasses',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Unisex',
      frameShape: 'Wayfarer',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Medium',
      prescriptionType: 'None',
      supportedPowers: '',
      collection: 'Classic',
      glassColor: 'Tinted',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Sunglasses'
    },
    {
      id: 19,
      name: 'Titan Oval Rimmed Eyeglasses',
      description: 'For Men, Size: Medium',
      price: 1800,
      image: 'path_to_image_19.jpg',
      brand: 'Titan',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Medium',
      gender: 'Men',
      frameShape: 'Oval',
      material: 'Plastic',
      frameWidth: 'Medium',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-3.00 to +2.00',
      collection: 'Modern',
      glassColor: 'Clear',
      subCollection: 'Signature',
      frameWidthValue: 140,
      productType: 'Eyeglasses'
    },
    {
      id: 20,
      name: 'Oakley Crosslink Zero Eyeglasses',
      description: 'For Men, Size: Large',
      price: 5200,
      image: 'path_to_image_20.jpg',
      brand: 'Oakley',
      category: 'Full Rim',
      color: 'Black',
      frameSize: 'Large',
      gender: 'Men',
      frameShape: 'Rectangle',
      material: 'Plastic',
      frameWidth: 'Wide',
      ageGroup: 'Adults',
      weightGroup: 'Light',
      prescriptionType: 'Single Vision',
      supportedPowers: '-4.00 to +3.00',
      collection: 'Sport',
      glassColor: 'Clear',
      subCollection: 'Limited Edition',
      frameWidthValue: 145,
      productType: 'Eyeglasses'
    }
  ];
  